server:
  port: 8080

logging:
  level:
    ROOT: WARN
    org.celltinel: DEBUG

spring:
  application:
    name: ms-e2e-encryption
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #issue with swagger & actuator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/payments
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

swagger:
  title: E2E Encryption API
  description: The api is used for E2E encryption
  default-include-pattern: "/.*"

security:
  publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfC4oX8MZT7C/vcQljwyP4rs4U31AjZC2HxV7BfU9BA9i+K1bu00NIZQKFBOQ9novxq7Gs1sDABA+Ei62O1mfJME8CAUSAjEowwepMrVm20YH/3fGFDeXFjC9cVslQBM9ALTRVq7tpPwW5rXQlWIactXFuSzqrbbYllhvA/Tu7sLayfUkNLK0k++9jUuNqSKhxPrldPIyz83xrVZE3oQ/Aqy98X5FkzMBe9CosJjYUGI3tJDEvkr1UBMZzengmJrTxQ+aMFOkQPgdA/PrL5GUVeyCQG4b4b+Y1J/96tUvBiJfRFMMoHKEERFOWiS8FviBGrbAVSAGS8dfYs4KZM5kwIDAQAB"
  privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJ8LihfwxlPsL+9xCWPDI/iuzhTfUCNkLYfFXsF9T0ED2L4rVu7TQ0hlAoUE5D2ei/GrsazWwMAED4SLrY7WZ8kwTwIBRICMSjDB6kytWbbRgf/d8YUN5cWML1xWyVAEz0AtNFWru2k/BbmtdCVYhpy1cW5LOqtttiWWG8D9O7uwtrJ9SQ0srST772NS42pIqHE+uV08jLPzfGtVkTehD8CrL3xfkWTMwF70KiwmNhQYje0kMS+SvVQExnN6eCYmtPFD5owU6RA+B0D8+svkZRV7IJAbhvhv5jUn/3q1S8GIl9EUwygcoQREU5aJLwW+IEatsBVIAZLx19izgpkzmTAgMBAAECggEAD7x9dsBCxAT/BwVTupFYTRFTYj9D73cxAFO4ElzNEHPPh/4Tq2A6qDkrN+kCIFFzzKiVmgIWAF1osrBgNxVQ3jZKtTeavP5J7Ha+UJMp0CHRNnT/FJMAsOuNzb8jtfy/AmjR896dMB4ZJdpMGfQ2XCAnWjZaNdxn/iL+9bu6AS/voXijdL2vZhNxk86Vl9cXxEt3yLU6D3nnSSGLviOsCtlyGJVrj4GFOwnCobrsQUioYXVVJlQGIhrLaYUDxKb7WiXh3qP1ZSTV8UUKbMMuZyVANUcEtSv7CYacdfp6xLb0t8ULdslMONgriGVB0dCYfy43DTSNQAdMnQcJcZJUIQKBgQD4dWwmyS76zjy/TSKkW/eaz8EAD0po0WJx/7+WFBbPO3EJObmtCqHqNWGLPM6vOsnUFQLKA4zW03kHz/0aUurHizMHgs3STYvSCDOC3Lp0HOaC9TtwI4HsG9bsUKX3LCUaAVFjhCtNBHAmCxaJe4CjieMZrutsYt5KH1Qqpa+ggwKBgQDQEddNd2EJOR3kx5eBj9nrlhPn9Sq/CEAv2EMqIAzHNxOgHdC9FhcFE4Yp6hwbZu+G91cjDxBGdq3HAZPQUpGn0acqim1kpgHzv5Lt1Mv4lgHVX4FohO4NcQ5MywPsqntout8tNqVWl2nVQ9XpOJUmh21tPMZ9zXJtyzWTUxOVsQKBgHW7tp7+cEualMCVvZeimMb8MVlk5X6b0YlxhgiIxnI2mY6kku6DfkwsNWe0TcBNHDxqJGMzoXZeyRhBn47swaICvRCPFBbWdi31gus8ywGgfD6MFDlEKhmG66YZZTul6ILVIwsEIzygoL/2Oxy0sDVObpXKBHbctrbq94gp8PofAoGALqNxITobFBgrbTaX7UCzVi1DtQCtXjiZOqA9HdolQxpDWeaU/W1QJ6Eit450UmgWVKhobcFYopLDjRH7cfywDW/fCpgQwTi8w0gzxP+n4MavDobj2OvC+FxZGjl/XbMxCl6o29ed4/T4kgcskaRPOl2s14mB7Hz6o0WjcqxyfWECgYEAliksGBOK5JvQ+jHffmjZpa95T6ZyWYFdEzm6Fdg4Mf95d+D/vJ51xVbd0bYvGl8Xs5VQClYVvTle+Bdn2Xkd2bHwtPB7vd+LJ7ExAmuboGECJbX62n98BIB9G+XtEGJtlFKJE5PLtpajZJarhmSfMrC6huEu/WztY9YMj3yl1qY="